server:
  port: 1000
  
spring:
  application:
    name: GAMES-MS
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_jpa_db
    username: root
    password: root@123

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
PLAYERS-MS:
  ribbon:
    eureka:
      enabled:false
    listOfServers: localhost:1100,localhost:1200, localhost:1300
    ServerListRefreshInterval: 1500